package com.fashion_app.closet_api.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    FILE_NOT_FOUND,
    OUTFIT_NOT_FOUND,
    UNAUTHORIZED,
    EMPTY_WARDROBE,
    INVALID_REQUEST,
    IMAGE_STORAGE_FAILED,
    CALENDAR_API_FAILED,
    WEATHER_API_FAILED,
    IMAGE_PROCESSING_FAILED,
    INTERNAL_ERROR,
    INVALID_EMAIL_FORMAT,
    EMAIL_ALREADY_EXISTS,
    INVALID_VERIFICATION_CODE,
    VERIFICATION_CODE_EXPIRED,
    ACCOUNT_ALREADY_VERIFIED,
    ACCOUNT_NOT_VERIFIED
}
